#!/bin/bash
# Brew Install
BREW_PATH=~/github/dotfiles/Brewfile
if [ $1 == "cask" ]; then
  brew cask install $2
  if grep -q "^cask install $2$" $BREW_PATH; then
    echo "Already in brewfile, skip adding"
  else
    echo "Adding to brewfile..."
    echo 'cask install '$2 >> $BREW_PATH
  fi
else
  brew install $1
  if grep -q "^install $1$" $BREW_PATH; then
    echo "Already in brewfile, skip adding"
  else
    echo "Adding to brewfile..."
    echo 'install '$1 >> $BREW_PATH
  fi
fi
