#!/bin/bash
# Brew Clean
BREW_PATH=~/github/dotfiles/Brewfile
echo $BREW_PATH
if [ $1 == "cask" ]; then
  brew cask uninstall $2
  echo "Removing from brewfile..."
  grep -v "^cask install $2$" $BREW_PATH > $BREW_PATH.tmp
else
  brew uninstall $1
  brew uninstall $(join <(brew leaves) <(brew deps $1))
  echo "Removing from brewfile..."
  grep -v "^install $1$" $BREW_PATH > $BREW_PATH.tmp
fi
mv $BREW_PATH.tmp $BREW_PATH
