#!/bin/bash
# Brew Clean

if [ $1 == "cask" ]; then
  brew cask uninstall $2
  echo "Removing from brewfile..."
  grep -v "^cask install $2$" ~/github/dotfiles/Brewfile > ~/github/dotfiles/Brewfile.tmp
else
  brew uninstall $1
  brew uninstall $(join <(brew leaves) <(brew deps $1))
  echo "Removing from brewfile..."
  grep -v "^install $1$" ~/github/dotfiles/Brewfile > ~/github/dotfiles/Brewfile.tmp
fi
mv ~/github/dotfiles/Brewfile.tmp ~/github/dotfiles/Brewfile
